# Generated by Django 5.1.7 on 2025-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=255)),
                ('remedy_name', models.CharField(max_length=255)),
                ('severity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
