# Generated by Django 5.1.7 on 2025-03-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedy',
            name='remedy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
